[mysql1]
DB_HOST = "mysql02-farm1.kinghost.net"
DB_USER = "habilidade11"
DB_PASSWORD = "Sales123"
DB_NAME = "habilidade11"

[mysql2]
DB_HOST = "mysql02-farm1.kinghost.net"
DB_USER = "habilidade12"
DB_PASSWORD = "Sales123"
DB_NAME = "habilidade12"
